export const UPLOAD_FILE = "UPLOAD_FILE";
export const UPLOAD_FILE_SUCCESS = "UPLOAD_FILE_SUCCESS";
export const UPLOAD_FILE_FAILED = "UPLOAD_FILE_FAILED";

export const WS_INIT_CONNECTION = 'WS_INIT_CONNECTION';
export const WS_CLOSE_CONNECTION = 'WS_CLOSE_CONNECTION';

export const WS_FILE_PROCESSED = 'WS_FILE_PROCESSED';